### ISSUE TITLE
Create Card

### ISSUE THREAD

**Issue by maximiliangustmann** [maximiliangustmann/capstone-project#1]
## Value statement - a requirement, not a solution
As a **user** 
I need **a card** 
so that **I can see information about my consumed medium** 

## Description (Text, Scribble, Wireframe, Design)
Creating a first page with a basic card, which shows information about the last consumed medium.
<img width="475" alt="Screenshot 2020-08-26 at 17 00 49" src="https://user-images.githubusercontent.com/67927174/91413005-cfd09a00-e84a-11ea-9206-f2adf9b67dba.png">
## Acceptance criteria
- [ ] (Card contains all the necessary information)

## Tasks
- [ ] (Create feature branch)
- [ ] (Create card component in storybook)
- [ ] (Write component test)
- [ ] (Add component to app)
- [ ] (Create feature branch)
- [ ] (Add styling)
- [ ] (Write integration tests w/ cypress)

## Size
small
