### ISSUE TITLE
Delete review

### ISSUE THREAD

**Issue by maximiliangustmann** [maximiliangustmann/capstone-project#13]
## Value statement - a requirement, not a solution
As a **user** 
I need **to delete a review** 
so that **I can fix mistakes or delete unecessary information** 

## Description (Text, Scribble, Wireframe, Design)
<img width="453" alt="Screenshot 2020-09-13 at 14 42 34" src="https://user-images.githubusercontent.com/67927174/93018358-78168a80-f5cf-11ea-9c91-762587421e7d.png">

## Acceptance criteria
- [ ] Review is deleted after click on delete button

## Tasks
- [ ] Add delete button
- [ ] Write delete button logik
- [ ] Write integration tests w/ Cypress

## Size
low
