### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by maximiliangustmann** [maximiliangustmann/capstone-project#14]
## Value statement - a requirement, not a solution
As a **user** 
I need **have a form validation** 
so that **I don't accidentally forget an input field or submit wrong values** 

## Description (Text, Scribble, Wireframe, Design)
Add validation to the form component.
## Acceptance criteria
- [ ] Submit is only possible after filling all the inputs
- [ ] Error message if an input is missing
- [ ] Rating must be submitted in the correct form
## Tasks
- [ ] Validation for text inputs
- [ ] Error message for text inputs
- [ ] Validation for rating input
- [ ] Error message for rating input

## Size
medium

**Comment by karstenlenz** [comment]
QS result:
I couldn't break the form. Obviously the styling is missing, but it works. I noticed 2 things:

- if you enter a space in the rating input and then a number it won't be accepted. Either automatically remove the space or stop the user from entering spaces in the rating input.
- It is enough to just enter one letter in each input. For some parts like summary or lessons, you might want to add a minimum length.

**Comment by carolinwagner** [comment]
QA: 
with simply typing a space the user can bypass the form validation in all forms but the rating form
