### ISSUE TITLE
Dropdown categorie input

### ISSUE THREAD

**Issue by maximiliangustmann** [maximiliangustmann/capstone-project#15]
## Value statement - a requirement, not a solution
As a **user** 
I need **to have dropdown options for the category input** 
so that **I can assign my review to the correct category** 

## Description (Text, Scribble, Wireframe, Design)
Changing the category input to a dropdown menu instead of a text input. The user can choose between book, film, series, audio book and podcast.
## Acceptance criteria
- [ ] When selecting the category input a dropdown menu should appear
- [ ] When selecting a dropdown option, this option should fill the input field

## Tasks
- [ ] Change category input to dropdown

## Size
low

**Comment by jennydely** [comment]
QA: The dropdown menue is working very good and all categories save and load correctly
