### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by maximiliangustmann** [maximiliangustmann/capstone-project#21]
## Value statement - a requirement, not a solution
As a **user** 
I need **Navigation** 
so that **I can get to the different pages ** 

## Description (Text, Scribble, Wireframe, Design)
<img width="401" alt="Screenshot 2020-09-21 at 15 05 05" src="https://user-images.githubusercontent.com/67927174/93769983-e5ec3300-fc1b-11ea-97d0-f6f1a5190a17.png">

## Acceptance criteria
- [ ] Navigation on the category sides work

## Tasks
- [ ] Create different pages
- [ ] Create Navigation component with storybook
- [ ] Display Navigation component on category pages
- [ ] Route the links
- [ ] Test routing with cypress

## Size
medium
