### ISSUE TITLE
Category Filter

### ISSUE THREAD

**Issue by maximiliangustmann** [maximiliangustmann/capstone-project#22]
## Value statement - a requirement, not a solution
As a **user** 
I need **to filter the category's** 
so that **I can see specific information** 

## Description (Text, Scribble, Wireframe, Design)
Create pages for the five category's and display the reviews given the chosen category input on these separate pages.
## Acceptance criteria
- [ ] Display the category on the matching page
- [ ] Display no other category on that page

## Tasks
- [ ] Write filter logic
- [ ] Display filter logic on the sides

## Size
medium
