### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by maximiliangustmann** [maximiliangustmann/capstone-project#23]
## Value statement - a requirement, not a solution
As a **user** 
I need **an appealing homepage** 
so that **I have fun using the app** 

## Description (Text, Scribble, Wireframe, Design)
<img width="399" alt="Screenshot 2020-09-21 at 14 57 37" src="https://user-images.githubusercontent.com/67927174/93769967-e1277f00-fc1b-11ea-81fb-f812817e7109.png">
## Acceptance criteria
- [ ] Navigation links on the homepage work

## Tasks
- [ ] Create Icon links on homepage
- [ ] Route the links
- [ ] Test routing with cypress

## Size
medium
