### ISSUE TITLE
List of reviews from json data

### ISSUE THREAD

**Issue by maximiliangustmann** [maximiliangustmann/capstone-project#3]
## Value statement - a requirement, not a solution
As a **user** 
I need **to see a list of my reviews** 
so that **that I can see more than one review** 

## Description (Text, Scribble, Wireframe, Design)
<img width="515" alt="Screenshot 2020-08-28 at 12 37 56" src="https://user-images.githubusercontent.com/67927174/91551978-5361b800-e92b-11ea-830d-d170cb0326f0.png">

## Acceptance criteria
- [ ] Multiple reviews can be shown by scrolling down

## Tasks
- [ ] create feature branch
- [ ] create json file with the data
- [ ] display data from multiple reviews
- [ ] add styling (scrolling)

## Size
low
