### ISSUE TITLE
Create new review

### ISSUE THREAD

**Issue by maximiliangustmann** [maximiliangustmann/capstone-project#4]
## Value statement - a requirement, not a solution
As a **user** 
I need **to add new reviews** 
so that **I can consume and store even more information** 

## Description (Text, Scribble, Wireframe, Design)
<img width="1023" alt="Screenshot 2020-08-28 at 16 44 58" src="https://user-images.githubusercontent.com/67927174/91580817-ef9cb680-e94d-11ea-9fd5-93e9c31b93d4.png">

## Acceptance criteria
- [ ] The form is found at the path "/create"
- [ ] Create button leads to "/create"
- [ ] Home button leads to "/"
- [ ] The form reacts on submit (Enter key or button press)
- [ ] The first input has focus at start
- [ ] Go back to "/" after submit
- [ ] The form is cleared after submit
- [ ] The new review is added at the end

## Tasks
- [ ] Create feature branch
- [ ] Create button component in storybook
- [ ] Write button component test
- [ ] Implement create button to app
- [ ] Add button routing
- [ ] Add button styling
- [ ] Create form component in storybook
- [ ] Write form component test
- [ ] Implement form component to app
- [ ] Add form routing
- [ ] Add form styling
- [ ] Integration test w/ cypress

## Size
high
