### ISSUE TITLE
Local storage

### ISSUE THREAD

**Issue by maximiliangustmann** [maximiliangustmann/capstone-project#5]
## Value statement - a requirement, not a solution
As a **user** 
I need **to save the data** 
so that **I can see the reviews I made in the past** 

## Description (Text, Scribble, Wireframe, Design)
Save the data in a local storage
## Acceptance criteria
- [ ] Reviews should be seen, even if the page is closed and reopened later on

## Tasks
- [ ] Implement local storage to App
- [ ] Integretaion test w/ cypress

## Size
medium
